[package]
name = "portifolio-server"
version = "0.1.0"
authors = ["lsunsi"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"

[dependencies.diesel]
version = "1.4.4"
features = ["postgres", "r2d2"]
