[package]
name = "portifolio-server"
version = "0.1.0"
authors = ["lsunsi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
