name: release

on:
  push:
    branches: [master]

jobs:
  release-server:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: cargo-${{ hashFiles('server/Cargo.lock') }}
          restore-keys: cargo-
      - name: Cache builds
        uses: actions/cache@v2
        with:
          path: server/target
          key: cargo-build-${{ hashFiles('server/Cargo.lock') }}
          restore-keys: cargo-build-
      - name: Install proper rust toolchain
        run: rustup install 1.46.0
      - name: Build release binary
        run: cargo +1.46.0 build --target x86_64-unknown-linux-gnu --release --locked --target-dir target
      - name: Compress release binary
        run: gzip -v -c -9 -f ./target/x86_64-unknown-linux-gnu/release/portifolio-server > portifolio-server.gz
      - name: Set tag name from date
        run: echo "::set-env name=DATE_TAG::$(date +'%Y-%m-%d/%H')"
      - name: Set body text from commit log
        run: echo "::set-env name=BODY::$(git log $(git describe --tags --abbrev=0)..@ --oneline --decorate=no)"
      - name: Create GitHub release
        id: create-release
        uses: actions/create-release@v1
        with:
          release_name: ${{ env.DATE_TAG }}
          tag_name: ${{ env.DATE_TAG }}
          body: ${{ env.BODY }}
          draft: true
      - name: Upload GitHub release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_content_type: application/gzip
          asset_path: ./server/portifolio-server.gz
          asset_name: portifolio-server.gz
